### PR TITLE
brendan coates blog post

### PR DESCRIPTION
**Pull request by ablwr**
The date for this is set for 2017-09-19, which means the Jekyll site will not show it in production until that time. So once this is done with review, it's good to be merged and deployed but the blog won't appear until the 19th.

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
We let the PR open up to Monday, in case there are other changes.

**Comment by ablwr** [comment]
Great thanks!!

**Comment by ablwr** [comment]
LGTM

**Comment by GuillaumeRoques** [comment]
It's online : https://mediaarea.net/MediaConch/2017/09/19/interview-with-brendan-coates/

**Comment by ablwr** [comment]
thank you!

**Pull request merged**
