### PR TITLE
adds local installation instructions

### PR DESCRIPTION
**Pull request by ablwr**
@dericed please test if I gave these instructions correctly

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
in instructions, it may be good to say which version you need (or was tested). e.g. I tried to install with Ruby 2.4 and json 1.8.3, mandatory for github-pages, fails to build.

**Comment by ablwr** [comment]
OK, I'll scope it out. Thanks @JeromeMartinez, that's a good suggestion. I can't test this until this evening, please hold until then!

**Comment by ablwr** [comment]
Added a Ruby version, although Ruby's bundler should really take care of the rest (re: `json` version). I had trouble installing fresh using an older version of Ruby, although could be specific to my setup and package management, but Ruby 2.3 and onward had no trouble.

@dericed was running into problems related to `nokogiri`... a notorious Ruby issue.

**Comment by JeromeMartinez** [comment]
When I try, I am having lot of dependencies issues.
I have to manually install them, up to json... which is incompatible with Ruby 2.4 (2.4 is "2.3 and onward"), as [previously said](https://github.com/MediaArea/MediaConch-Website/pull/77#issuecomment-318112716).

I am on Windows.
I installed Ruby 2.4.1 from https://rubyinstaller.org/downloads/
Then

```
>path=%PATH%;C:\Ruby24-x64\bin

>gem install bundler
Successfully installed bundler-1.15.3

>gem install github-pages
[...]
Successfully installed github-pages-146
[...]
72 gems installed

>jekyll build
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find RedCloth-4.2.9 in any of the sources (Bundler::GemNotFound)

>gem install RedCloth -v 4.2.9
Successfully installed RedCloth-4.2.9

C:\Programmation\MediaConch-Website>jekyll build
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find i18n-0.7.0 in any of the sources (Bundler::GemNotFound)

>gem install i18n -v 0.7.0
Successfully installed i18n-0.7.0

>jekyll build
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find json-1.8.3 in any of the sources (Bundler::GemNotFound)

>gem install json -v 1.8.3
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.
        
>bundle
[...]
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
```
([full log](https://gist.github.com/JeromeMartinez/ee200c7746eda3bece46c76435cf7646))
        
Issue is documented https://github.com/flori/json/issues/303

With Ruby 2.3 Windows, I have that:
```
>bundle

[!] There was an error parsing `Gemfile`: SSL_connect returned=1 errno=0 state=error: certificate verify failed. Bundler cannot continue.

 #  from C:/Programmation/MediaConch-Website/Gemfile:5
 #  -------------------------------------------
 #  gem 'octopress'
 >  gem 'github-pages' #  source "https://rubygems.org"
 #  -------------------------------------------
```

Note: few months ago I succeeded to install and run it, but I don't remember which version (of Ruby and github-pages), and there was no `bundler`.

We also have https://github.com/MediaArea/MediaConch-Website/blob/master/HowToBuild.txt which adds github-pages, maybe a single and complete place for install?

If I remember well, @GuillaumeRoques also had hard time installing it on CentOS.

Which OS was tested? Which version of Ruby?

**Comment by ablwr** [comment]
I'm sorry that I am so uninformed on running Ruby on Windows. You shouldn't have to install everything one-by-one like that, `bundler` should take care of everything for you. It pulls from the Gemfile. `bundler` is the package manager, like Javascript's `npm`. 

I am going to send a PR to delete the Gemfile.lock we have checked into this repo -- that is not a necessary piece of code and it could be impacting the install.

**Comment by ablwr** [comment]
Oh, and I'm on a Mac, Sierra, and running Ruby `ruby-2.3.0`. I tried it on a different Mac, but it's also running Sierra and also defaulting to 2.3... 😅

**Comment by ablwr** [comment]
Should I put those instructions in the HowToBuild.txt?

**Comment by JeromeMartinez** [comment]
> Should I put those instructions in the HowToBuild.txt?

If I merge this PR, we would have 2 places for instructions, and both incomplete (e.g. no github-pages in the readme, no bundler in the howto), not good.
Having the install instructions in readme is fine for me, common practice and directly visible on GitHub.

I suggest to move all in 1 place (readme) + info about the tested platform with OS and versions of ruby/bundler/github-pages/everything we install from the command line (as we got issues on other platforms), and next year we'll see if it is worth it to work more on it with e.g. testing more platforms and versions.

**Comment by ablwr** [comment]
Will update. Fine to delete HowToBuild.txt?

**Comment by JeromeMartinez** [comment]
> Fine to delete HowToBuild.txt?

Yes, if content is moved to readme.

**Comment by ablwr** [comment]
:D

**Pull request merged**
