### PR TITLE
notimetowait2.md - removes schedule section fixes #99

### LINKED ISSUE #99: NTTW2 - Should schedule section be removed?
Hi,

I wonder if the schedule section should be removed now that the program section has the link to the spreadsheet? https://mediaarea.net/MediaConch/notimetowait2.html

Initially, I went looking for that spreadsheet in the 'schedule' section.

### PR DESCRIPTION
**Pull request by kieranjol**
Just gave this a whirl just in case... Looks like the 'program' section has everything already.

### CODE REVIEW

**Comment by dericed** [comment]
LGTM, I think having a reference to the 2016 program somewhere could be helpful though.

**Comment by JeromeMartinez** [comment]
> I think having a reference to the 2016 program somewhere could be helpful though.

A link to NTTW1 page?

**Comment by kieranjol** [comment]
I agree with the NTTW1 reference - I was going to leave that in but was afraid that linking to two schedules would be confusing. Feel free to edit the pull request.

**Comment by kieranjol** [comment]
Perhaps a link to the NTTW1 page could come at the end of the WHAT section?

Information about the 2016 No Time to Wait may be viewed [here](
https://mediaarea.net/MediaConch/notimetowait.html)

**Comment by JeromeMartinez** [comment]
I agree with this update proposal.

**Comment by kieranjol** [comment]
I just added another commit there that adds the link to the nttw1 page.

**Review by dericed — APPROVED** [review]

**Comment by JeromeMartinez** [comment]
it is online.

**Comment by kieranjol** [comment]
:) thx

**Pull request merged**
