### PR TITLE
Newsletter 6

### PR DESCRIPTION
**Pull request by foundscapes**

### CODE REVIEW

**Comment by ablwr** [comment]
Oh hello! Can newsletter 6 also be added to the main Newsletters page?

**Comment by foundscapes** [comment]
I created a PR but am not exactly sure how to make this happen as I am
still learning GH, all advice/help welcome!

On Sat, Jul 9, 2016 at 8:15 PM, Ashley notifications@github.com wrote:

> Oh hello! Can newsletter 6 also be added to the main Newsletters page?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/MediaArea/MediaConch-Website/pull/33#issuecomment-231547944,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACINn4WFQRIGk5SD4soyFi5mthJ20Rtbks5qT-VLgaJpZM4JIoqp
> .

## 

“I can't understand why people are frightened of new ideas. I'm frightened
of the old ones.”

John Cage

**Comment by JeromeMartinez** [comment]
Only @GuillaumeRoques and @JeromeMartinez have access to the official server.

It is online now : [Newsletter #6](https://mediaarea.net/MediaConch/2016/07/07/mediaconch-newsletter-no-6/)

**Comment by ablwr** [comment]
Oh yeah, I was referring to making sure that the newsletter would also show up on this page: https://mediaarea.net/MediaConch/newsletters.html

And it does! Thanks both!

**Comment by foundscapes** [comment]
Thank you!!

On Sat, Jul 9, 2016 at 8:30 PM, Ashley notifications@github.com wrote:

> Oh yeah, I was referring to making sure that the newsletter would also
> show up on this page: https://mediaarea.net/MediaConch/newsletters.html
> 
> And it does! Thanks both!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/MediaArea/MediaConch-Website/pull/33#issuecomment-231548673,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACINn1ZJWW7SWH8ekdAOhggG-P0kyGBlks5qT-jGgaJpZM4JIoqp
> .

## 

“I can't understand why people are frightened of new ideas. I'm frightened
of the old ones.”

John Cage

**Comment by JeromeMartinez** [comment]
Sorry, I read too quick.
[it is in "Newsletters" category](https://github.com/MediaArea/MediaConch-Website/commit/8a965095d4e9a07326fa79b6e4de61789f17962d#diff-dbe13e869fd4a3d795ce3f90ffc6a76fR5) so it is in the newsletters page.

**Pull request merged**
