### PR TITLE
update hashtag and give a link

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
https://twitter.com/hashtag/nttw17 is maybe a simpler URL

**Comment by ablwr** [comment]
+1 Jerome

**Comment by JeromeMartinez** [comment]
I am late for the poll but 'NTTW' is more or less free too.
Year or not Year...

**Comment by dericed** [comment]
I suggest stalling on this. The original poll was appending with a 2nd poll that included an option to support the outcome of the first poll. See https://twitter.com/dericed/status/915275014215229441 and https://twitter.com/dericed/status/915277655917912064. The result was 8 votes with #nttw17 (6 in poll 1 and 2 in the 2nd poll to support the first) and then 7 votes for #nttw2, but the poll is broken if anyone voting for #nttw17 in the 1st also voted for supporting the first poll in the 2nd. (I messed the logic up here).

There was a recount poll at https://twitter.com/dericed/status/915697528036904962 which is currently open. But there also suggests for #nttw here and also ##nottime2wait in the twitter thread which were unconsidered.

I regret using a twitter poll straight away and should have used something more dynamic to support ongoing consideration of write-ins. So I suggest ... another poll:

- [ ] I close the PR and tiptoe away
- [x] let the 3rd poll proceed and use the results

**Comment by JeromeMartinez** [comment]
Weird usage of the checkboxes :).
Please do another poll and we see.

**Comment by dericed** [comment]
closing this in favor of discussion in program committee, reopen if needed

**Pull request closed without merging**
