### PR TITLE
NTTW2 Hotels

### PR DESCRIPTION
**Pull request by JeromeMartinez**

### CODE REVIEW

**Comment by ablwr** [comment]
These four lines should have two white spaces at the end of each, which is what causes a linebreak in Markdown.

**Comment by JeromeMartinez** [comment]
this is the goal, in order to have a linebreak in the HTML output, better visibility than all on 1 line.
Not good from your point of view?

**Comment by JeromeMartinez** [comment]
I mean: the 2 white spaces are there, so why "should have two white spaces"?

**Comment by ablwr** [comment]
Oh they weren't visible in the preview -- then it's 👍 from me! (Can't speak for the content).

**Review by ablwr — APPROVED** [review]

**Pull request merged**
