### PR TITLE
blog about policy update

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by dericed** [comment]
IIUC the url will be https://mediaarea.net/MediaConch/2016/10/04/policy-refactor. Passing this to @foundscapes so please correct if that's not the URL after merge.

**Comment by dericed** [comment]
@foundscapes noticed an issue with the image, now fixed.

**Comment by GuillaumeRoques** [comment]
@dericed @foundscapes url is almost good just missing the trailing slash

**Comment by ablwr** [comment]
Bring on the deployment! 😎

**Comment by ablwr** [comment]
Thumbs up, confirmed online. Great!

**Comment by ablwr** [comment]
Oh the ``` backticks aren't showing up for the XML segments!

**Comment by GuillaumeRoques** [comment]
Yes there is problem with ``` conversion, I fix them manually but need a real fix for next deployments.
Also image is too large : 750px max

**Pull request merged**
