### PR TITLE
adds kieran o leary blog post

### PR DESCRIPTION
**Pull request by ablwr**
For posting Monday or Tuesday. cc @kieranjol

### CODE REVIEW

**Comment by kieranjol** [comment]
Thx Ashley. As for the screenshot, that's actually just my home laptop, I could probably try to take shots of one of our workstations in the IFI on Monday. I just took a look at Kathryn's screenshots and they are much more interesting. Might not matter though.

**Review by dericed — APPROVED** [review]

**Comment by ablwr** [comment]
Great, I can add them if you send 'em over!

**Comment by JeromeMartinez** [comment]
Is all ready to go live e.g. concerning pictures?

**Comment by kieranjol** [comment]
Hi,

I probably won't be able to get extra pics today, so if ye are happy with
that one, then it's ready go?


On 24 Jul 2017 11:05, "Jérôme Martinez" <notifications@github.com> wrote:

Is all ready to go live e.g. concerning pictures?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MediaArea/MediaConch-Website/pull/74#issuecomment-317377335>,
or mute the thread

**Comment by ablwr** [comment]
Ready to go!

**Comment by ablwr** [comment]
Thanks! When deployed, let me know and I will send/promote.

**Comment by GuillaumeRoques** [comment]
It's deployed on prod

**Pull request merged**
