### PR TITLE
updates fixity.html to be represented as blog

### PR DESCRIPTION
**Pull request by ablwr**
Hello. This takes https://mediaarea.net/MediaConch/fixity.html and turns it into a blog post and updates the English to be more "native speaker."

### CODE REVIEW

**Comment by ablwr** [comment]
@dericed mentioned he might have some more things to add, but I think there's a lot to test out here!

**Comment by JeromeMartinez** [comment]
Great!
Blog post or dedicated page?
(maybe first a blog post then we copy and update a dedicated page)

**Comment by ablwr** [comment]
Yeah, I was thinking the same. Shipping the blog post will generate the appropriate HTML to link to a dedicated page. I used the full URL paths so it should work without modification.

**Comment by ablwr** [comment]
I could also add a dedicated page here in the repo -- don't know how that would conflict since fixity.html already exists (manually) in deployed production.

**Comment by JeromeMartinez** [comment]
No conflict, please proceed

**Comment by ablwr** [comment]
OK. Duplicated and added appropriate frontloaded YAML to deliver to fixity.html. Maybe it's silly to have two pages that do the same thing, but whatever! Double the promotion...?

**Comment by GuillaumeRoques** [comment]
It's a bad idea to have duplicated content (Google don't like that at all), maybe we can remove the fixity page and redirect the url to the blog post.

**Comment by JeromeMartinez** [comment]
The top level page will be updated with new features, not the blog post.

**Comment by ablwr** [comment]
It doesn't have to be a blog post so we could remove it from _posts and just have the fixity.html!

**Comment by JeromeMartinez** [comment]
I prefer fixity.html for long term.

**Comment by ablwr** [comment]
Viola!

**Comment by GuillaumeRoques** [comment]
I've seen it to late but there is an error on the link of audio corrected image :
https://github.com/MediaArea/MediaConch-Website/pull/52/files#diff-1348bd225318896e1f55f34d7dc5767cR79
I fixed the generated page (and deployed it on prod) but please fix the link in another PR.

**Comment by ablwr** [comment]
Eep, thanks, re-opening!

**Pull request merged**
